name: Prepare Release Candidate

on:
  push:
    branches:
      - main

permissions:
  contents: write # for committing and pushing to release-candidate branch
  pull-requests: write # for creating/updating PRs

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Fetch all history for version calculation
          token: ${{ secrets.GITHUB_TOKEN }} # Use default token for checkout

      - name: Set up Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run prepare-release script
        run: node scripts/prepare-release.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
